/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const GetAllMemberResponse: core.serialization.ObjectSchema<
    serializers.GetAllMemberResponse.Raw,
    Attio.GetAllMemberResponse
> = core.serialization.object({
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).WorkspaceMember)
    ),
});

export declare namespace GetAllMemberResponse {
    interface Raw {
        data: serializers.WorkspaceMember.Raw[];
    }
}
