/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const GetMemberResponse: core.serialization.ObjectSchema<
    serializers.GetMemberResponse.Raw,
    Attio.GetMemberResponse
> = core.serialization.object({
    data: core.serialization.lazyObject(async () => (await import("../../..")).WorkspaceMember),
});

export declare namespace GetMemberResponse {
    interface Raw {
        data: serializers.WorkspaceMember.Raw;
    }
}
