/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const WorkspaceMemberWorkspaceMemberId: core.serialization.Schema<
    serializers.WorkspaceMemberWorkspaceMemberId.Raw,
    Attio.WorkspaceMemberWorkspaceMemberId
> = core.serialization.string();

export declare namespace WorkspaceMemberWorkspaceMemberId {
    type Raw = string;
}
