/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const WorkspaceMemberAvatarUrl: core.serialization.Schema<
    serializers.WorkspaceMemberAvatarUrl.Raw,
    Attio.WorkspaceMemberAvatarUrl
> = core.serialization.string().optional();

export declare namespace WorkspaceMemberAvatarUrl {
    type Raw = string | null | undefined;
}
