/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const WorkspaceMemberAccessLevel: core.serialization.Schema<
    serializers.WorkspaceMemberAccessLevel.Raw,
    Attio.WorkspaceMemberAccessLevel
> = core.serialization.enum_(["admin", "member", "suspended"]);

export declare namespace WorkspaceMemberAccessLevel {
    type Raw = "admin" | "member" | "suspended";
}
