/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const WorkspaceMemberWorkspaceId: core.serialization.Schema<
    serializers.WorkspaceMemberWorkspaceId.Raw,
    Attio.WorkspaceMemberWorkspaceId
> = core.serialization.string();

export declare namespace WorkspaceMemberWorkspaceId {
    type Raw = string;
}
