/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const WorkspaceMemberLastName: core.serialization.Schema<
    serializers.WorkspaceMemberLastName.Raw,
    Attio.WorkspaceMemberLastName
> = core.serialization.string();

export declare namespace WorkspaceMemberLastName {
    type Raw = string;
}
