/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../core";

export const WorkspaceMemberCreatedAt: core.serialization.Schema<
    serializers.WorkspaceMemberCreatedAt.Raw,
    Attio.WorkspaceMemberCreatedAt
> = core.serialization.string();

export declare namespace WorkspaceMemberCreatedAt {
    type Raw = string;
}
