/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const GetObjectResponse: core.serialization.ObjectSchema<
    serializers.particle.GetObjectResponse.Raw,
    Attio.particle.GetObjectResponse
> = core.serialization.object({
    data: core.serialization.lazyObject(async () => (await import("../../../../..")).particle.Object),
});

export declare namespace GetObjectResponse {
    interface Raw {
        data: serializers.particle.Object.Raw;
    }
}
