/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const Object: core.serialization.ObjectSchema<serializers.particle.Object.Raw, Attio.particle.Object> =
    core.serialization.object({
        id: core.serialization.lazyObject(async () => (await import("../../../../..")).particle.ObjectId),
        apiSlug: core.serialization.property(
            "api_slug",
            core.serialization.lazy(async () => (await import("../../../../..")).particle.ObjectApiSlug)
        ),
        singularNoun: core.serialization.property(
            "singular_noun",
            core.serialization.lazy(async () => (await import("../../../../..")).particle.ObjectSingularNoun)
        ),
        pluralNoun: core.serialization.property(
            "plural_noun",
            core.serialization.lazy(async () => (await import("../../../../..")).particle.ObjectPluralNoun)
        ),
        createdAt: core.serialization.property(
            "created_at",
            core.serialization.lazy(async () => (await import("../../../../..")).particle.ObjectCreatedAt)
        ),
    });

export declare namespace Object {
    interface Raw {
        id: serializers.particle.ObjectId.Raw;
        api_slug?: serializers.particle.ObjectApiSlug.Raw;
        singular_noun?: serializers.particle.ObjectSingularNoun.Raw;
        plural_noun?: serializers.particle.ObjectPluralNoun.Raw;
        created_at: serializers.particle.ObjectCreatedAt.Raw;
    }
}
