/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const ObjectObjectId: core.serialization.Schema<
    serializers.particle.ObjectObjectId.Raw,
    Attio.particle.ObjectObjectId
> = core.serialization.string();

export declare namespace ObjectObjectId {
    type Raw = string;
}
