/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const ObjectPluralNoun: core.serialization.Schema<
    serializers.particle.ObjectPluralNoun.Raw,
    Attio.particle.ObjectPluralNoun
> = core.serialization.string().optional();

export declare namespace ObjectPluralNoun {
    type Raw = string | null | undefined;
}
