/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const ObjectApiSlug: core.serialization.Schema<
    serializers.particle.ObjectApiSlug.Raw,
    Attio.particle.ObjectApiSlug
> = core.serialization.string().optional();

export declare namespace ObjectApiSlug {
    type Raw = string | null | undefined;
}
