/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class AttioTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, AttioTimeoutError.prototype);
    }
}
