/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const ObjectId: core.serialization.ObjectSchema<serializers.particle.ObjectId.Raw, Attio.particle.ObjectId> =
    core.serialization.object({
        workspaceId: core.serialization.property(
            "workspace_id",
            core.serialization.lazy(async () => (await import("../../../../..")).particle.ObjectWorkspaceId)
        ),
        objectId: core.serialization.property(
            "object_id",
            core.serialization.lazy(async () => (await import("../../../../..")).particle.ObjectObjectId)
        ),
    });

export declare namespace ObjectId {
    interface Raw {
        workspace_id: serializers.particle.ObjectWorkspaceId.Raw;
        object_id: serializers.particle.ObjectObjectId.Raw;
    }
}
