/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Attio } from "@fern-api/attio";
import * as core from "../../../../../../core";

export const ObjectWorkspaceId: core.serialization.Schema<
    serializers.particle.ObjectWorkspaceId.Raw,
    Attio.particle.ObjectWorkspaceId
> = core.serialization.string();

export declare namespace ObjectWorkspaceId {
    type Raw = string;
}
