/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A unique, human-readable slug to access the Object through URLs and API calls. Formatted in snake case.
 */
export type ObjectApiSlug = string | undefined;
