/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the Member is suspended or not and what level of privileges they have inside the Workspace. We do not delete Workspace Members so that you can successfully attribute past actions to suspended Members.
 */
export type WorkspaceMemberAccessLevel = "admin" | "member" | "suspended";

export const WorkspaceMemberAccessLevel = {
    Admin: "admin",
    Member: "member",
    Suspended: "suspended",
} as const;
