/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Attio } from "@fern-api/attio";

export interface WorkspaceMember {
    id: Attio.WorkspaceMemberId;
    firstName: Attio.WorkspaceMemberFirstName;
    lastName: Attio.WorkspaceMemberLastName;
    avatarUrl?: Attio.WorkspaceMemberAvatarUrl;
    emailAddress: Attio.WorkspaceMemberEmailAddress;
    createdAt: Attio.WorkspaceMemberCreatedAt;
    accessLevel: Attio.WorkspaceMemberAccessLevel;
}
