/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Attio } from "@fern-api/attio";

export interface AttioObject {
    id: Attio.particle.ObjectId;
    apiSlug?: Attio.particle.ObjectApiSlug;
    singularNoun?: Attio.particle.ObjectSingularNoun;
    pluralNoun?: Attio.particle.ObjectPluralNoun;
    createdAt: Attio.particle.ObjectCreatedAt;
}
