/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Attio } from "@fern-api/attio";

export interface ObjectId {
    workspaceId: Attio.particle.ObjectWorkspaceId;
    objectId: Attio.particle.ObjectObjectId;
}
