/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const AttioEnvironment = {
    Production: "https://api.attio.com/",
} as const;

export type AttioEnvironment = typeof AttioEnvironment.Production;
