/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Objects } from "../resources/objects/client/Client";

export declare namespace Particle {
    interface Options {
        environment?: environments.AttioEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class Particle {
    constructor(private readonly options: Particle.Options) {}

    private _objects: Objects | undefined;

    public get objects(): Objects {
        return (this._objects ??= new Objects(this.options));
    }
}
