/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Object } from "../resources/object/client/Client";

export declare namespace Particle {
    interface Options {
        environment?: environments.AttioEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class Particle {
    constructor(private readonly options: Particle.Options) {}

    private _object: Object | undefined;

    public get object(): Object {
        return (this._object ??= new Object(this.options));
    }
}
